import 'car.dart';
import 'brand.dart';
import 'user.dart';

class MockData {
  static const defaultInspection = InspectionReport(
    overallScore: 4.8,
    totalPoints: 200,
    passed: true,
    categories: [
      InspectionCategory(name: 'Engine & Transmission', score: 95),
      InspectionCategory(name: 'Exterior & Body', score: 88),
      InspectionCategory(name: 'Interior & Electronics', score: 92),
      InspectionCategory(name: 'Tyres & Suspension', score: 85),
    ],
  );

  static const defaultDealer = DealerSummary(
    id: 'd1',
    name: 'Premium Auto Hub',
    rating: 4.9,
    city: 'Mumbai',
    badge: 'Trusted Dealer',
    initial: 'P',
  );

  static const List<Car> cars = [
    Car(
      id: 1,
      name: 'Mercedes-Benz C-Class',
      brand: 'Mercedes',
      year: 2022,
      price: '32.5L',
      km: '18,200',
      fuel: 'Petrol',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Mumbai',
      rating: 4.8,
      color: '#C0C0C0',
      badge: 'Premium',
      emi: '₹48,200/mo',
      inspection: defaultInspection,
      dealer: defaultDealer,
    ),
    Car(
      id: 2,
      name: 'BMW 3 Series',
      brand: 'BMW',
      year: 2021,
      price: '38.9L',
      km: '24,500',
      fuel: 'Diesel',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Delhi',
      rating: 4.7,
      color: '#1E3A5F',
      badge: 'Luxury',
      emi: '₹57,800/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd2', name: 'Elite Motors', rating: 4.8, city: 'Delhi', initial: 'E'),
    ),
    Car(
      id: 3,
      name: 'Audi A4',
      brand: 'Audi',
      year: 2023,
      price: '41.2L',
      km: '8,900',
      fuel: 'Petrol',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Bangalore',
      rating: 4.9,
      color: '#2D2D2D',
      badge: 'Like New',
      emi: '₹61,200/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd3', name: 'Prestige Cars', rating: 4.9, city: 'Bangalore', initial: 'P'),
    ),
    Car(
      id: 4,
      name: 'Toyota Fortuner',
      brand: 'Toyota',
      year: 2022,
      price: '34.8L',
      km: '32,100',
      fuel: 'Diesel',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Chennai',
      rating: 4.6,
      color: '#F5F5DC',
      badge: 'Popular',
      emi: '₹51,600/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd4', name: 'Trust Auto', rating: 4.7, city: 'Chennai', initial: 'T'),
    ),
    Car(
      id: 5,
      name: 'Hyundai Creta',
      brand: 'Hyundai',
      year: 2023,
      price: '14.5L',
      km: '12,400',
      fuel: 'Petrol',
      transmission: 'Manual',
      owner: '1st',
      city: 'Pune',
      rating: 4.5,
      color: '#8B0000',
      badge: 'Best Value',
      emi: '₹21,500/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd5', name: 'City Motors', rating: 4.6, city: 'Pune', initial: 'C'),
    ),
    Car(
      id: 6,
      name: 'Tata Harrier',
      brand: 'Tata',
      year: 2023,
      price: '18.9L',
      km: '15,800',
      fuel: 'Diesel',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Hyderabad',
      rating: 4.4,
      color: '#1B4332',
      badge: 'Trending',
      emi: '₹28,000/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd6', name: 'Mega Cars', rating: 4.5, city: 'Hyderabad', initial: 'M'),
    ),
    Car(
      id: 7,
      name: 'Kia Seltos',
      brand: 'Kia',
      year: 2024,
      price: '16.2L',
      km: '5,200',
      fuel: 'Petrol',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Mumbai',
      rating: 4.7,
      color: '#4A4A4A',
      badge: 'Almost New',
      emi: '₹24,000/mo',
      inspection: defaultInspection,
      dealer: defaultDealer,
    ),
    Car(
      id: 8,
      name: 'Mahindra XUV700',
      brand: 'Mahindra',
      year: 2023,
      price: '22.5L',
      km: '19,600',
      fuel: 'Diesel',
      transmission: 'Automatic',
      owner: '1st',
      city: 'Delhi',
      rating: 4.6,
      color: '#8B4513',
      badge: 'Top Pick',
      emi: '₹33,400/mo',
      inspection: defaultInspection,
      dealer: DealerSummary(id: 'd7', name: 'Royal Auto', rating: 4.7, city: 'Delhi', initial: 'R'),
    ),
  ];

  static const List<Brand> brands = [
    Brand(name: 'Mercedes', emoji: '⭐', count: 245),
    Brand(name: 'BMW', emoji: '🔵', count: 198),
    Brand(name: 'Audi', emoji: '🔘', count: 176),
    Brand(name: 'Toyota', emoji: '🔴', count: 412),
    Brand(name: 'Hyundai', emoji: '🅷', count: 389),
    Brand(name: 'Tata', emoji: '🇹', count: 356),
    Brand(name: 'Kia', emoji: '🅺', count: 287),
    Brand(name: 'Mahindra', emoji: '🅼', count: 334),
  ];

  static const currentUser = AppUser(
    id: 'u1',
    name: 'Karthi M',
    initials: 'KM',
    email: 'karthi@example.com',
    phone: '+91 98765 43210',
    city: 'Chennai',
    memberSince: '2024',
    tier: 'Gold',
  );

  static const List<String> filterChips = ['All', 'SUV', 'Sedan', 'Hatchback', 'Luxury', 'EV'];

  static const List<Map<String, dynamic>> profileMenuItems = [
    {'icon': 'car', 'label': 'My Bookings', 'count': 2},
    {'icon': 'heart', 'label': 'Saved Cars', 'count': 5},
    {'icon': 'compare', 'label': 'Compare History', 'count': 0},
    {'icon': 'shield', 'label': 'Insurance & Warranty', 'count': 0},
    {'icon': 'phone', 'label': 'Support Center', 'count': 0},
    {'icon': 'bell', 'label': 'Notifications', 'count': 3},
  ];

  static const List<Map<String, String>> trustItems = [
    {'icon': 'shield', 'text': '200-Point Quality Inspection'},
    {'icon': 'check', 'text': '5-Day Money Back Guarantee'},
    {'icon': 'car', 'text': 'Free Home Test Drive'},
    {'icon': 'phone', 'text': '24/7 Customer Support'},
  ];

  static const List<Map<String, String>> onboardingSlides = [
    {
      'emoji': '🔍',
      'title': 'Discover Your\nDream Car',
      'description': 'Browse 10,000+ verified used cars from trusted dealers across India',
    },
    {
      'emoji': '🛡️',
      'title': '200-Point\nInspection',
      'description': 'Every car undergoes rigorous quality checks. Buy with complete confidence',
    },
    {
      'emoji': '💰',
      'title': 'Best Price\nGuarantee',
      'description': 'Transparent pricing with no hidden charges. Easy EMI options available',
    },
  ];
}
