services:
  - type: web
    name: searchanycars
    runtime: node
    region: oregon
    plan: free
    rootDir: searchanycars.com
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECURE
        value: "true"
      - key: SMTP_PASS
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
