import { db } from './db.js'
import bcrypt from 'bcryptjs'

const defaultCategories = [
  { name: 'Hatchback', slug: 'hatchback', vehicleType: 'Hatchback' },
  { name: 'Sedan', slug: 'sedan', vehicleType: 'Sedan' },
  { name: 'SUV', slug: 'suv', vehicleType: 'SUV' },
  { name: 'MUV', slug: 'muv', vehicleType: 'MUV' },
  { name: 'Coupe', slug: 'coupe', vehicleType: 'Coupe' },
  { name: 'Pickup', slug: 'pickup', vehicleType: 'Pickup' },
  { name: 'Luxury Sedan', slug: 'luxury-sedan', vehicleType: 'Luxury Sedan' },
  { name: 'Luxury SUV', slug: 'luxury-suv', vehicleType: 'Luxury SUV' },
]

const defaultFilterDefinitions = [
  { key: 'brand', label: 'Brand', type: 'text', options: [] },
  { key: 'fuel_type', label: 'Fuel Type', type: 'select', options: ['Petrol', 'Diesel', 'Electric', 'Hybrid', 'CNG', 'LPG'] },
  { key: 'transmission_type', label: 'Transmission', type: 'select', options: ['Manual', 'Automatic', 'CVT', 'DCT', 'AMT'] },
  { key: 'ownership_type', label: 'Ownership Type', type: 'select', options: ['First', 'Second', 'Third', 'Fourth+'] },
  { key: 'seller_type', label: 'Seller Type', type: 'select', options: ['Dealer', 'Individual', 'Certified Dealer'] },
  { key: 'listing_price_min', label: 'Min Price (INR)', type: 'number', options: [] },
  { key: 'listing_price_max', label: 'Max Price (INR)', type: 'number', options: [] },
  { key: 'model_year_min', label: 'Min Model Year', type: 'number', options: [] },
  { key: 'model_year_max', label: 'Max Model Year', type: 'number', options: [] },
  { key: 'total_km_driven_max', label: 'Max KM Driven', type: 'number', options: [] },
  { key: 'location_city', label: 'City', type: 'text', options: [] },
  { key: 'body_style', label: 'Body Type', type: 'select', options: ['Hatchback', 'Sedan', 'SUV', 'MUV', 'Coupe', 'Pickup'] },
  { key: 'exterior_color', label: 'Color', type: 'select', options: ['White', 'Black', 'Silver', 'Grey', 'Red', 'Blue', 'Brown', 'Beige'] },
]

const sampleListings = [
  {
    listingCode: 'SAC-1001',
    title: '2022 Hyundai Creta SX(O)',
    brand: 'Hyundai',
    model: 'Creta',
    variant: 'SX(O)',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Polar White',
    interiorColor: 'Black',
    listingPriceInr: 1450000,
    negotiable: 0,
    estimatedMarketValueInr: 1520000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Delhi',
    registrationCity: 'New Delhi',
    totalKmDriven: 25432,
    mileageKmpl: 16.8,
    engineType: '1.5L Turbo Petrol',
    engineCapacityCc: 1482,
    powerBhp: 158,
    transmissionType: 'Automatic',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '10.25',
    locationCity: 'New Delhi',
    locationState: 'Delhi',
    dealerRating: 4.8,
    inspectionStatus: 'Completed',
    inspectionScore: 92,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 342,
    favoritesCount: 67,
    leadCount: 28,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Top-spec Creta with panoramic sunroof, ADAS features, ventilated seats, and Bose sound system. Single owner, full Hyundai service history. Immaculate condition.',
  },
  {
    listingCode: 'SAC-1002',
    title: '2023 Maruti Suzuki Baleno Alpha',
    brand: 'Maruti Suzuki',
    model: 'Baleno',
    variant: 'Alpha',
    modelYear: 2023,
    registrationYear: 2023,
    vehicleType: 'Hatchback',
    bodyStyle: 'Hatchback',
    exteriorColor: 'Nexa Blue',
    interiorColor: 'Black & Grey',
    listingPriceInr: 820000,
    negotiable: 0,
    estimatedMarketValueInr: 870000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Maharashtra',
    registrationCity: 'Mumbai',
    totalKmDriven: 12800,
    mileageKmpl: 22.4,
    engineType: '1.2L DualJet Petrol',
    engineCapacityCc: 1197,
    powerBhp: 89,
    transmissionType: 'Manual',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '9',
    locationCity: 'Mumbai',
    locationState: 'Maharashtra',
    dealerRating: 4.6,
    inspectionStatus: 'Completed',
    inspectionScore: 95,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 256,
    favoritesCount: 42,
    leadCount: 19,
    promotionTier: 'Featured',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Almost new Baleno Alpha with heads-up display, 360-degree camera, and SmartPlay Pro+ infotainment. Excellent fuel efficiency for city driving.',
  },
  {
    listingCode: 'SAC-1003',
    title: '2021 Tata Nexon XZ+ Dark Edition',
    brand: 'Tata',
    model: 'Nexon',
    variant: 'XZ+ Dark Edition',
    modelYear: 2021,
    registrationYear: 2021,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Atlas Black',
    interiorColor: 'Blackstone',
    listingPriceInr: 985000,
    negotiable: 0,
    estimatedMarketValueInr: 1050000,
    ownershipType: 'First',
    sellerType: 'Dealer',
    registrationState: 'Karnataka',
    registrationCity: 'Bengaluru',
    totalKmDriven: 38500,
    mileageKmpl: 17.2,
    engineType: '1.2L Turbo Revotron',
    engineCapacityCc: 1199,
    powerBhp: 120,
    transmissionType: 'Manual',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 8,
    serviceHistoryAvailable: 1,
    airbagsCount: 4,
    infotainmentScreenSize: '7',
    locationCity: 'Bengaluru',
    locationState: 'Karnataka',
    dealerRating: 4.5,
    inspectionStatus: 'Completed',
    inspectionScore: 88,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 198,
    favoritesCount: 34,
    leadCount: 15,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80'
    ],
    description: '5-star GNCAP rated compact SUV with Dark Edition styling. Features connected car tech, sunroof, and automatic climate control. Well maintained.',
  },
  {
    listingCode: 'SAC-1004',
    title: '2022 Honda City ZX CVT',
    brand: 'Honda',
    model: 'City',
    variant: 'ZX CVT',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'Sedan',
    bodyStyle: 'Sedan',
    exteriorColor: 'Platinum White Pearl',
    interiorColor: 'Black',
    listingPriceInr: 1280000,
    negotiable: 0,
    estimatedMarketValueInr: 1350000,
    ownershipType: 'First',
    sellerType: 'Individual',
    registrationState: 'Tamil Nadu',
    registrationCity: 'Chennai',
    totalKmDriven: 18900,
    mileageKmpl: 18.4,
    engineType: '1.5L i-VTEC',
    engineCapacityCc: 1498,
    powerBhp: 121,
    transmissionType: 'CVT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '8',
    locationCity: 'Chennai',
    locationState: 'Tamil Nadu',
    dealerRating: 0,
    inspectionStatus: 'Completed',
    inspectionScore: 91,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 278,
    favoritesCount: 51,
    leadCount: 22,
    promotionTier: 'Featured',
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Top-spec City with lane watch camera, Honda Connect, LED headlamps, and sunroof. Smooth CVT transmission perfect for city and highway. Single owner.',
  },
  {
    listingCode: 'SAC-1005',
    title: '2023 Kia Seltos HTX+',
    brand: 'Kia',
    model: 'Seltos',
    variant: 'HTX+',
    modelYear: 2023,
    registrationYear: 2023,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Gravity Grey',
    interiorColor: 'Indigo Pera',
    listingPriceInr: 1590000,
    negotiable: 0,
    estimatedMarketValueInr: 1650000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Telangana',
    registrationCity: 'Hyderabad',
    totalKmDriven: 9800,
    mileageKmpl: 16.5,
    engineType: '1.5L Turbo GDI',
    engineCapacityCc: 1497,
    powerBhp: 158,
    transmissionType: 'DCT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '10.25',
    locationCity: 'Hyderabad',
    locationState: 'Telangana',
    dealerRating: 4.9,
    inspectionStatus: 'Completed',
    inspectionScore: 96,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 410,
    favoritesCount: 89,
    leadCount: 35,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Almost new Seltos with ADAS Level 2 features, ventilated seats, 360-degree camera, and Bose 8-speaker system. Under 10K km. Extended warranty available.',
  },
  {
    listingCode: 'SAC-1006',
    title: '2022 Mahindra XUV700 AX7 Luxury',
    brand: 'Mahindra',
    model: 'XUV700',
    variant: 'AX7 Luxury',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Everest White',
    interiorColor: 'Tan Leatherette',
    listingPriceInr: 1890000,
    negotiable: 0,
    estimatedMarketValueInr: 1980000,
    ownershipType: 'First',
    sellerType: 'Dealer',
    registrationState: 'Maharashtra',
    registrationCity: 'Pune',
    totalKmDriven: 32100,
    mileageKmpl: 14.5,
    engineType: '2.2L mHawk Diesel',
    engineCapacityCc: 2184,
    powerBhp: 185,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 7,
    infotainmentScreenSize: '10.25',
    locationCity: 'Pune',
    locationState: 'Maharashtra',
    dealerRating: 4.4,
    inspectionStatus: 'Completed',
    inspectionScore: 89,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 356,
    favoritesCount: 72,
    leadCount: 30,
    promotionTier: 'Featured',
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1606611013016-969c19ba27ea?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Fully loaded XUV700 with ADAS, panoramic sunroof, 7-seater with captain seats, Sony 3D sound, and AdrenoX connected car tech.',
  },
  {
    listingCode: 'SAC-1007',
    title: '2022 Toyota Fortuner Legender',
    brand: 'Toyota',
    model: 'Fortuner',
    variant: 'Legender',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Dual Tone White Pearl',
    interiorColor: 'Maroon',
    listingPriceInr: 3950000,
    negotiable: 0,
    estimatedMarketValueInr: 4100000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Gujarat',
    registrationCity: 'Ahmedabad',
    totalKmDriven: 28500,
    mileageKmpl: 10.2,
    engineType: '2.8L GD Diesel',
    engineCapacityCc: 2755,
    powerBhp: 204,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 7,
    infotainmentScreenSize: '8',
    locationCity: 'Ahmedabad',
    locationState: 'Gujarat',
    dealerRating: 4.7,
    inspectionStatus: 'Completed',
    inspectionScore: 93,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 520,
    favoritesCount: 98,
    leadCount: 42,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Premium Fortuner Legender with exclusive front grille, sequential turn indicators, ambient lighting, and Toyota warranty remaining. Bulletproof reliability.',
  },
  {
    listingCode: 'SAC-1008',
    title: '2021 Volkswagen Polo TSI GT',
    brand: 'Volkswagen',
    model: 'Polo',
    variant: 'TSI GT',
    modelYear: 2021,
    registrationYear: 2021,
    vehicleType: 'Hatchback',
    bodyStyle: 'Hatchback',
    exteriorColor: 'Sunset Red',
    interiorColor: 'Black',
    listingPriceInr: 780000,
    negotiable: 0,
    estimatedMarketValueInr: 830000,
    ownershipType: 'Second',
    sellerType: 'Individual',
    registrationState: 'Delhi',
    registrationCity: 'New Delhi',
    totalKmDriven: 45200,
    mileageKmpl: 18.2,
    engineType: '1.0L TSI Turbo',
    engineCapacityCc: 999,
    powerBhp: 110,
    transmissionType: 'Manual',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 8,
    serviceHistoryAvailable: 1,
    airbagsCount: 4,
    infotainmentScreenSize: '6.5',
    locationCity: 'New Delhi',
    locationState: 'Delhi',
    dealerRating: 0,
    inspectionStatus: 'Completed',
    inspectionScore: 85,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 145,
    favoritesCount: 23,
    leadCount: 8,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1471479917193-f00955256257?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Legendary Polo GT TSI - the enthusiast\'s hatchback. Peppy turbo engine, solid build quality, and fun to drive. Well maintained with genuine service records.',
  },
  {
    listingCode: 'SAC-1009',
    title: '2023 MG Hector Sharp CVT',
    brand: 'MG',
    model: 'Hector',
    variant: 'Sharp CVT',
    modelYear: 2023,
    registrationYear: 2023,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Starry Black',
    interiorColor: 'Sangria Red & Black',
    listingPriceInr: 1720000,
    negotiable: 0,
    estimatedMarketValueInr: 1800000,
    ownershipType: 'First',
    sellerType: 'Dealer',
    registrationState: 'Rajasthan',
    registrationCity: 'Jaipur',
    totalKmDriven: 15600,
    mileageKmpl: 14.8,
    engineType: '1.5L Turbo Petrol',
    engineCapacityCc: 1451,
    powerBhp: 141,
    transmissionType: 'CVT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '14',
    locationCity: 'Jaipur',
    locationState: 'Rajasthan',
    dealerRating: 4.3,
    inspectionStatus: 'Completed',
    inspectionScore: 90,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 267,
    favoritesCount: 45,
    leadCount: 18,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1606611013016-969c19ba27ea?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Feature-rich Hector with 14-inch touchscreen, panoramic sunroof, ventilated seats, wireless charging, and i-SMART connected tech.',
  },
  {
    listingCode: 'SAC-1010',
    title: '2022 Skoda Kushaq Style 1.5 TSI',
    brand: 'Skoda',
    model: 'Kushaq',
    variant: 'Style 1.5 TSI',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Tornado Red',
    interiorColor: 'Black',
    listingPriceInr: 1380000,
    negotiable: 0,
    estimatedMarketValueInr: 1450000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Karnataka',
    registrationCity: 'Bengaluru',
    totalKmDriven: 22400,
    mileageKmpl: 15.6,
    engineType: '1.5L TSI EVO',
    engineCapacityCc: 1498,
    powerBhp: 150,
    transmissionType: 'DCT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '10',
    locationCity: 'Bengaluru',
    locationState: 'Karnataka',
    dealerRating: 4.5,
    inspectionStatus: 'Completed',
    inspectionScore: 91,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 189,
    favoritesCount: 38,
    leadCount: 14,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Sporty Kushaq with 1.5 TSI engine and 7-speed DSG. European build quality, ventilated seats, sunroof, and My Skoda Connect.',
  },
  {
    listingCode: 'SAC-1011',
    title: '2020 Renault Kwid Climber AMT',
    brand: 'Renault',
    model: 'Kwid',
    variant: 'Climber AMT',
    modelYear: 2020,
    registrationYear: 2020,
    vehicleType: 'Hatchback',
    bodyStyle: 'Hatchback',
    exteriorColor: 'Outback Bronze',
    interiorColor: 'Grey',
    listingPriceInr: 380000,
    negotiable: 0,
    estimatedMarketValueInr: 420000,
    ownershipType: 'Second',
    sellerType: 'Individual',
    registrationState: 'Uttar Pradesh',
    registrationCity: 'Lucknow',
    totalKmDriven: 52000,
    mileageKmpl: 24.1,
    engineType: '1.0L SCe',
    engineCapacityCc: 999,
    powerBhp: 68,
    transmissionType: 'AMT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 7,
    serviceHistoryAvailable: 0,
    airbagsCount: 2,
    infotainmentScreenSize: '8',
    locationCity: 'Lucknow',
    locationState: 'Uttar Pradesh',
    dealerRating: 0,
    inspectionStatus: 'Completed',
    inspectionScore: 78,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 98,
    favoritesCount: 12,
    leadCount: 6,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Budget-friendly AMT hatchback with great mileage. Touchscreen infotainment, rear parking camera. Perfect for city commuting.',
  },
  {
    listingCode: 'SAC-1012',
    title: '2022 BMW X5 xDrive40i',
    brand: 'BMW',
    model: 'X5',
    variant: 'xDrive40i',
    modelYear: 2022,
    registrationYear: 2022,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Arctic White',
    interiorColor: 'Cognac Vernasca Leather',
    listingPriceInr: 5199000,
    negotiable: 0,
    estimatedMarketValueInr: 5400000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Karnataka',
    registrationCity: 'Bengaluru',
    totalKmDriven: 21450,
    mileageKmpl: 11.2,
    engineType: '3.0L Turbo I6',
    engineCapacityCc: 2998,
    powerBhp: 335,
    transmissionType: 'Automatic',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 9,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '12.3',
    locationCity: 'Bengaluru',
    locationState: 'Karnataka',
    dealerRating: 4.8,
    inspectionStatus: 'Completed',
    inspectionScore: 94,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    viewsCount: 430,
    favoritesCount: 85,
    leadCount: 32,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Premium family SUV with panoramic roof, Harman Kardon sound, gesture control, wireless Apple CarPlay, and complete BMW service history.',
  },
  {
    listingCode: 'SAC-1013',
    title: '2023 Tata Punch Adventure',
    brand: 'Tata',
    model: 'Punch',
    variant: 'Adventure',
    modelYear: 2023,
    registrationYear: 2023,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Tornado Blue',
    interiorColor: 'Grey & Black',
    listingPriceInr: 780000,
    negotiable: 0,
    estimatedMarketValueInr: 840000,
    ownershipType: 'First',
    sellerType: 'Dealer',
    registrationState: 'Maharashtra',
    registrationCity: 'Mumbai',
    totalKmDriven: 8500,
    mileageKmpl: 19.2,
    engineType: '1.2L Revotron',
    engineCapacityCc: 1199,
    powerBhp: 86,
    transmissionType: 'AMT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 1,
    airbagsCount: 4,
    infotainmentScreenSize: '7',
    locationCity: 'Mumbai',
    locationState: 'Maharashtra',
    dealerRating: 4.2,
    inspectionStatus: 'Completed',
    inspectionScore: 97,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 320,
    favoritesCount: 56,
    leadCount: 20,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1617704548623-340376564e68?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Almost new Tata Punch with 5-star safety rating. Perfect micro-SUV with high ground clearance, connected car features, and rugged styling.',
  },
  {
    listingCode: 'SAC-1014',
    title: '2021 Hyundai i20 Asta(O)',
    brand: 'Hyundai',
    model: 'i20',
    variant: 'Asta(O)',
    modelYear: 2021,
    registrationYear: 2021,
    vehicleType: 'Hatchback',
    bodyStyle: 'Hatchback',
    exteriorColor: 'Starry Night',
    interiorColor: 'Dark Grey',
    listingPriceInr: 890000,
    negotiable: 0,
    estimatedMarketValueInr: 950000,
    ownershipType: 'First',
    sellerType: 'Individual',
    registrationState: 'Tamil Nadu',
    registrationCity: 'Chennai',
    totalKmDriven: 28700,
    mileageKmpl: 20.3,
    engineType: '1.0L Turbo GDI',
    engineCapacityCc: 998,
    powerBhp: 120,
    transmissionType: 'DCT',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 8,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '10.25',
    locationCity: 'Chennai',
    locationState: 'Tamil Nadu',
    dealerRating: 0,
    inspectionStatus: 'Completed',
    inspectionScore: 87,
    listingStatus: 'Active',
    featuredListing: 0,
    viewsCount: 156,
    favoritesCount: 29,
    leadCount: 11,
    promotionTier: 'Standard',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Premium hatchback with turbo performance, Bose sound, sunroof, wireless charging, and Blue Link connected car tech.',
  },
  {
    listingCode: 'SAC-1015',
    title: '2023 Maruti Suzuki Grand Vitara Alpha+',
    brand: 'Maruti Suzuki',
    model: 'Grand Vitara',
    variant: 'Alpha+ Hybrid',
    modelYear: 2023,
    registrationYear: 2023,
    vehicleType: 'SUV',
    bodyStyle: 'SUV',
    exteriorColor: 'Celestial Blue',
    interiorColor: 'Black & Blue',
    listingPriceInr: 1750000,
    negotiable: 0,
    estimatedMarketValueInr: 1830000,
    ownershipType: 'First',
    sellerType: 'Certified Dealer',
    registrationState: 'Delhi',
    registrationCity: 'New Delhi',
    totalKmDriven: 11200,
    mileageKmpl: 27.9,
    engineType: '1.5L Strong Hybrid',
    engineCapacityCc: 1462,
    powerBhp: 115,
    transmissionType: 'Automatic',
    fuelType: 'Hybrid',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 1,
    airbagsCount: 6,
    infotainmentScreenSize: '9',
    locationCity: 'New Delhi',
    locationState: 'Delhi',
    dealerRating: 4.7,
    inspectionStatus: 'Completed',
    inspectionScore: 95,
    listingStatus: 'Active',
    featuredListing: 1,
    viewsCount: 380,
    favoritesCount: 75,
    leadCount: 28,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1606611013016-969c19ba27ea?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=80'
    ],
    description: 'Class-leading 27.97 kmpl strong hybrid SUV. Head-up display, 360 camera, panoramic sunroof, wireless charging. Almost new condition.',
  },
]

const newCarListings = [
  {
    listingCode: 'SAC-NC-001',
    title: '2025 GLE 300d 4MATIC LWB',
    brand: 'Mercedes-Benz',
    model: 'GLE',
    variant: '300d 4MATIC LWB',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Obsidian Black Metallic',
    interiorColor: 'Macchiato Beige Nappa Leather',
    listingPriceInr: 9650000,
    negotiable: 0,
    estimatedMarketValueInr: 10100000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 12,
    mileageKmpl: 14.2,
    engineType: '2.0L Inline-4 Turbo Diesel',
    engineCapacityCc: 1950,
    powerBhp: 269,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 9,
    infotainmentScreenSize: '12.3',
    locationCity: 'Mumbai',
    locationState: 'Maharashtra',
    dealerRating: 4.9,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unregistered',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Brand new, unregistered GLE 300d with panoramic sunroof, MBUX infotainment, Burmester surround sound, ADAS Level 2, air suspension, and full manufacturer warranty. Zero kilometers.',
  },
  {
    listingCode: 'SAC-NC-002',
    title: '2025 C-Class C 200 AMG Line',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    variant: 'C 200 AMG Line',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'Sedan',
    bodyStyle: 'Luxury Sedan',
    exteriorColor: 'Selenite Grey Metallic',
    interiorColor: 'Black Artico Leather',
    listingPriceInr: 6200000,
    negotiable: 0,
    estimatedMarketValueInr: 6500000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 8,
    mileageKmpl: 16.9,
    engineType: '1.5L Turbo Petrol with EQ Boost',
    engineCapacityCc: 1496,
    powerBhp: 204,
    transmissionType: 'Automatic',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 7,
    infotainmentScreenSize: '11.9',
    locationCity: 'New Delhi',
    locationState: 'Delhi',
    dealerRating: 4.8,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unregistered',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Factory-fresh C 200 AMG Line with AMG body styling, 11.9-inch OLED display, digital cockpit, ambient lighting with 64 colors, and full manufacturer warranty.',
  },
  {
    listingCode: 'SAC-NC-003',
    title: '2025 BMW X3 xDrive20d M Sport',
    brand: 'BMW',
    model: 'X3',
    variant: 'xDrive20d M Sport',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Alpine White',
    interiorColor: 'Cognac Vernasca Leather',
    listingPriceInr: 7490000,
    negotiable: 0,
    estimatedMarketValueInr: 7800000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 22,
    mileageKmpl: 15.8,
    engineType: '2.0L TwinPower Turbo Diesel',
    engineCapacityCc: 1995,
    powerBhp: 197,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 6,
    infotainmentScreenSize: '14.9',
    locationCity: 'Bengaluru',
    locationState: 'Karnataka',
    dealerRating: 4.7,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Demo',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Dealer demo X3 with M Sport package, panoramic sunroof, Harman Kardon surround sound, BMW Live Cockpit Professional, and full BMW warranty. Under 25 km.',
  },
  {
    listingCode: 'SAC-NC-004',
    title: '2025 Audi Q5 45 TFSI quattro Technology',
    brand: 'Audi',
    model: 'Q5',
    variant: '45 TFSI quattro Technology',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Navarra Blue Metallic',
    interiorColor: 'Okapi Brown Fine Nappa Leather',
    listingPriceInr: 7190000,
    negotiable: 0,
    estimatedMarketValueInr: 7500000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 5,
    mileageKmpl: 13.5,
    engineType: '2.0L TFSI Turbo Petrol',
    engineCapacityCc: 1984,
    powerBhp: 249,
    transmissionType: 'Automatic',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 8,
    infotainmentScreenSize: '10.1',
    locationCity: 'Chennai',
    locationState: 'Tamil Nadu',
    dealerRating: 4.8,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unregistered',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1606611013016-969c19ba27ea?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Brand new Audi Q5 with quattro AWD, virtual cockpit, Matrix LED headlights, Bang & Olufsen 3D sound, and full Audi warranty. Zero registration.',
  },
  {
    listingCode: 'SAC-NC-005',
    title: '2025 Volvo XC60 B5 Ultimate',
    brand: 'Volvo',
    model: 'XC60',
    variant: 'B5 Ultimate',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Crystal White Pearl',
    interiorColor: 'Blond Nappa Leather',
    listingPriceInr: 7090000,
    negotiable: 0,
    estimatedMarketValueInr: 7400000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 15,
    mileageKmpl: 14.1,
    engineType: '2.0L Turbo Petrol Mild Hybrid',
    engineCapacityCc: 1969,
    powerBhp: 250,
    transmissionType: 'Automatic',
    fuelType: 'Hybrid',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 7,
    infotainmentScreenSize: '9',
    locationCity: 'Hyderabad',
    locationState: 'Telangana',
    dealerRating: 4.6,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unused',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Brand new XC60 with Bowers & Wilkins audio, air purifier, pilot assist, panoramic moonroof, and Volvo\'s industry-leading safety suite. Full factory warranty.',
  },
  {
    listingCode: 'SAC-NC-006',
    title: '2025 S-Class S 450d 4MATIC',
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    variant: 'S 450d 4MATIC',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'Sedan',
    bodyStyle: 'Luxury Sedan',
    exteriorColor: 'Onyx Black',
    interiorColor: 'Sienna Brown Exclusive Nappa',
    listingPriceInr: 18500000,
    negotiable: 0,
    estimatedMarketValueInr: 19200000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 3,
    mileageKmpl: 12.8,
    engineType: '3.0L Inline-6 Turbo Diesel',
    engineCapacityCc: 2925,
    powerBhp: 367,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 10,
    infotainmentScreenSize: '12.8',
    locationCity: 'Mumbai',
    locationState: 'Maharashtra',
    dealerRating: 5.0,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unregistered',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'The pinnacle of luxury — brand new S-Class with rear executive package, MBUX hyperscreen, Burmester 4D surround, active ambient lighting, and E-Active body control.',
  },
  {
    listingCode: 'SAC-NC-007',
    title: '2025 Toyota Land Cruiser LC 300 ZX',
    brand: 'Toyota',
    model: 'Land Cruiser',
    variant: 'LC 300 ZX',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Precious White Pearl',
    interiorColor: 'Sand Beige Semi-Aniline Leather',
    listingPriceInr: 22000000,
    negotiable: 0,
    estimatedMarketValueInr: 23500000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 0,
    mileageKmpl: 8.9,
    engineType: '3.3L V6 Twin-Turbo Diesel',
    engineCapacityCc: 3346,
    powerBhp: 305,
    transmissionType: 'Automatic',
    fuelType: 'Diesel',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 10,
    infotainmentScreenSize: '12.3',
    locationCity: 'New Delhi',
    locationState: 'Delhi',
    dealerRating: 4.9,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Unregistered',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'The legendary Land Cruiser — brand new, unregistered. Multi-terrain select, kinetic dynamic suspension, JBL premium audio, and Toyota\'s bulletproof reliability. Full factory warranty.',
  },
  {
    listingCode: 'SAC-NC-008',
    title: '2025 Porsche Cayenne Coupe',
    brand: 'Porsche',
    model: 'Cayenne',
    variant: 'Coupe',
    modelYear: 2025,
    registrationYear: null,
    vehicleType: 'SUV',
    bodyStyle: 'Luxury SUV',
    exteriorColor: 'Carrara White Metallic',
    interiorColor: 'Black/Bordeaux Red Leather',
    listingPriceInr: 15500000,
    negotiable: 0,
    estimatedMarketValueInr: 16200000,
    ownershipType: null,
    sellerType: 'Certified Dealer',
    registrationState: null,
    registrationCity: null,
    totalKmDriven: 18,
    mileageKmpl: 11.5,
    engineType: '3.0L V6 Turbo',
    engineCapacityCc: 2995,
    powerBhp: 353,
    transmissionType: 'Automatic',
    fuelType: 'Petrol',
    batteryCapacityKwh: null,
    overallConditionRating: 10,
    serviceHistoryAvailable: 0,
    airbagsCount: 8,
    infotainmentScreenSize: '12.3',
    locationCity: 'Bengaluru',
    locationState: 'Karnataka',
    dealerRating: 4.9,
    inspectionStatus: 'Factory New',
    inspectionScore: 100,
    listingStatus: 'Active',
    featuredListing: 1,
    isSplus: 1,
    isNewCar: 1,
    newCarType: 'Demo',
    viewsCount: 0,
    favoritesCount: 0,
    leadCount: 0,
    promotionTier: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1400&q=80',
    ],
    description: 'Dealer demo Cayenne Coupe with sport chrono package, PASM adaptive suspension, Bose surround sound, and panoramic roof system. Full Porsche warranty.',
  },
]

const createTables = () => {
  db.exec(`
    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      slug TEXT NOT NULL UNIQUE,
      vehicle_type TEXT NOT NULL,
      description TEXT DEFAULT '',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS filter_definitions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      key TEXT NOT NULL UNIQUE,
      label TEXT NOT NULL,
      type TEXT NOT NULL,
      options_json TEXT NOT NULL DEFAULT '[]'
    );

    CREATE TABLE IF NOT EXISTS category_filter_map (
      category_id INTEGER NOT NULL,
      filter_id INTEGER NOT NULL,
      PRIMARY KEY (category_id, filter_id),
      FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
      FOREIGN KEY (filter_id) REFERENCES filter_definitions(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS listings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      category_id INTEGER,
      listing_code TEXT NOT NULL UNIQUE,
      title TEXT NOT NULL,
      brand TEXT NOT NULL,
      model TEXT NOT NULL,
      variant TEXT DEFAULT '',
      model_year INTEGER,
      registration_year INTEGER,
      vehicle_type TEXT,
      body_style TEXT,
      exterior_color TEXT,
      interior_color TEXT,
      vin TEXT,
      engine_number TEXT,
      registration_number_masked TEXT,
      listing_price_inr REAL NOT NULL,
      negotiable INTEGER NOT NULL DEFAULT 0,
      original_onroad_price_inr REAL,
      estimated_market_value_inr REAL,
      minimum_expected_price_inr REAL,
      price_per_km_inr REAL,
      emi_estimate_inr_month REAL,
      down_payment_estimate_inr REAL,
      loan_available INTEGER DEFAULT 0,
      loan_interest_rate REAL,
      insurance_cost_estimate_inr REAL,
      annual_maintenance_cost_inr REAL,
      transfer_charges_inr REAL,
      rc_transfer_cost_inr REAL,
      documentation_charges_inr REAL,
      dealer_fees_inr REAL,
      delivery_charges_inr REAL,
      inspection_charges_inr REAL,
      extended_warranty_cost_inr REAL,
      accessory_value_added_inr REAL,
      previous_owners_count INTEGER,
      ownership_type TEXT,
      ownership_category TEXT,
      seller_type TEXT,
      ownership_transfer_ready INTEGER DEFAULT 0,
      registration_state TEXT,
      registration_city TEXT,
      registration_valid_till TEXT,
      road_tax_paid INTEGER DEFAULT 0,
      road_tax_valid_till TEXT,
      hypothecation_status TEXT,
      bank_finance_name TEXT,
      noc_available INTEGER DEFAULT 0,
      pollution_valid_till TEXT,
      insurance_status TEXT,
      insurance_type TEXT,
      insurance_valid_till TEXT,
      accident_history INTEGER DEFAULT 0,
      legal_case INTEGER DEFAULT 0,
      total_km_driven REAL,
      average_km_per_year REAL,
      mileage_kmpl REAL,
      city_mileage REAL,
      highway_mileage REAL,
      fuel_efficiency_rating REAL,
      engine_type TEXT,
      engine_capacity_cc REAL,
      power_bhp REAL,
      torque_nm REAL,
      cylinders_count INTEGER,
      transmission_type TEXT,
      drivetrain TEXT,
      turbocharged INTEGER DEFAULT 0,
      fuel_injection_type TEXT,
      emission_standard TEXT,
      fuel_type TEXT,
      fuel_tank_capacity_liters REAL,
      battery_capacity_kwh REAL,
      battery_health_percent REAL,
      battery_range_km REAL,
      charging_time TEXT,
      fast_charging_supported INTEGER DEFAULT 0,
      overall_condition_rating REAL,
      exterior_condition TEXT,
      interior_condition TEXT,
      engine_condition TEXT,
      tire_condition TEXT,
      brake_condition TEXT,
      suspension_condition TEXT,
      battery_condition TEXT,
      flood_damage INTEGER DEFAULT 0,
      accident_damage INTEGER DEFAULT 0,
      repainted_panels TEXT,
      rust_condition TEXT,
      service_history_available INTEGER DEFAULT 0,
      authorized_service_maintained INTEGER DEFAULT 0,
      last_service_date TEXT,
      last_service_cost_inr REAL,
      major_repairs_done INTEGER DEFAULT 0,
      warranty_remaining INTEGER DEFAULT 0,
      extended_warranty_available INTEGER DEFAULT 0,
      airbags_count INTEGER,
      abs INTEGER DEFAULT 0,
      ebd INTEGER DEFAULT 0,
      traction_control INTEGER DEFAULT 0,
      esc INTEGER DEFAULT 0,
      hill_assist INTEGER DEFAULT 0,
      lane_assist INTEGER DEFAULT 0,
      adaptive_cruise_control INTEGER DEFAULT 0,
      blind_spot_monitoring INTEGER DEFAULT 0,
      rear_parking_sensors INTEGER DEFAULT 0,
      rear_parking_camera INTEGER DEFAULT 0,
      camera_360 INTEGER DEFAULT 0,
      tpms INTEGER DEFAULT 0,
      isofix INTEGER DEFAULT 0,
      air_conditioning_type TEXT,
      heater INTEGER DEFAULT 0,
      leather_seats INTEGER DEFAULT 0,
      seat_material TEXT,
      seat_adjustment TEXT,
      ventilated_seats INTEGER DEFAULT 0,
      heated_seats INTEGER DEFAULT 0,
      sunroof INTEGER DEFAULT 0,
      ambient_lighting INTEGER DEFAULT 0,
      rear_ac_vents INTEGER DEFAULT 0,
      cruise_control INTEGER DEFAULT 0,
      keyless_entry INTEGER DEFAULT 0,
      push_start_button INTEGER DEFAULT 0,
      infotainment_screen_size TEXT,
      touchscreen INTEGER DEFAULT 0,
      apple_carplay INTEGER DEFAULT 0,
      android_auto INTEGER DEFAULT 0,
      bluetooth INTEGER DEFAULT 0,
      usb_ports_count INTEGER,
      navigation_system INTEGER DEFAULT 0,
      premium_sound_system INTEGER DEFAULT 0,
      speakers_count INTEGER,
      wireless_charging INTEGER DEFAULT 0,
      alloy_wheels INTEGER DEFAULT 0,
      wheel_size TEXT,
      fog_lamps INTEGER DEFAULT 0,
      led_headlights INTEGER DEFAULT 0,
      drls INTEGER DEFAULT 0,
      roof_rails INTEGER DEFAULT 0,
      spoiler INTEGER DEFAULT 0,
      auto_headlights INTEGER DEFAULT 0,
      rain_sensing_wipers INTEGER DEFAULT 0,
      power_folding_mirrors INTEGER DEFAULT 0,
      tire_brand TEXT,
      tire_size TEXT,
      tire_condition_percent REAL,
      spare_tire_available INTEGER DEFAULT 0,
      wheel_material TEXT,
      location_city TEXT,
      location_state TEXT,
      pickup_available INTEGER DEFAULT 0,
      delivery_available INTEGER DEFAULT 0,
      test_drive_available INTEGER DEFAULT 0,
      seller_name TEXT,
      dealer_rating REAL,
      dealer_verified INTEGER DEFAULT 0,
      contact_number TEXT,
      contact_email TEXT,
      seller_address TEXT,
      years_in_business INTEGER,
      images_json TEXT NOT NULL DEFAULT '[]',
      interior_images_json TEXT NOT NULL DEFAULT '[]',
      exterior_images_json TEXT NOT NULL DEFAULT '[]',
      engine_images_json TEXT NOT NULL DEFAULT '[]',
      tire_images_json TEXT NOT NULL DEFAULT '[]',
      damage_images_json TEXT NOT NULL DEFAULT '[]',
      view_360_url TEXT,
      video_walkaround_url TEXT,
      inspection_status TEXT,
      inspection_score REAL,
      inspection_report_url TEXT,
      platform_certified INTEGER DEFAULT 0,
      third_party_inspection_company TEXT,
      listing_status TEXT NOT NULL DEFAULT 'Active',
      featured_listing INTEGER NOT NULL DEFAULT 0,
      is_splus INTEGER NOT NULL DEFAULT 0,
      is_new_car INTEGER NOT NULL DEFAULT 0,
      new_car_type TEXT,
      views_count INTEGER DEFAULT 0,
      favorites_count INTEGER DEFAULT 0,
      lead_count INTEGER DEFAULT 0,
      promotion_tier TEXT,
      reason_for_sale TEXT,
      accessories_included TEXT,
      modifications TEXT,
      known_issues TEXT,
      additional_notes TEXT,
      specs_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
    );

    CREATE INDEX IF NOT EXISTS idx_listings_category_id ON listings(category_id);
    CREATE INDEX IF NOT EXISTS idx_listings_brand ON listings(brand);
    CREATE INDEX IF NOT EXISTS idx_listings_fuel_type ON listings(fuel_type);
    CREATE INDEX IF NOT EXISTS idx_listings_transmission_type ON listings(transmission_type);
    CREATE INDEX IF NOT EXISTS idx_listings_listing_price_inr ON listings(listing_price_inr);
    CREATE INDEX IF NOT EXISTS idx_listings_model_year ON listings(model_year);
    CREATE INDEX IF NOT EXISTS idx_listings_total_km_driven ON listings(total_km_driven);
    CREATE INDEX IF NOT EXISTS idx_listings_location_city ON listings(location_city);
    CREATE INDEX IF NOT EXISTS idx_listings_is_splus ON listings(is_splus);
    CREATE INDEX IF NOT EXISTS idx_listings_is_new_car ON listings(is_new_car);

    CREATE TABLE IF NOT EXISTS site_config (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL DEFAULT '{}',
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Users
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT UNIQUE,
      phone TEXT UNIQUE,
      name TEXT NOT NULL DEFAULT '',
      password_hash TEXT,
      role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin', 'user')),
      google_id TEXT UNIQUE,
      phone_verified INTEGER NOT NULL DEFAULT 0,
      email_verified INTEGER NOT NULL DEFAULT 0,
      avatar_url TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
    CREATE INDEX IF NOT EXISTS idx_users_google_id ON users(google_id);

    -- Sessions
    CREATE TABLE IF NOT EXISTS sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      refresh_token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      ip_address TEXT,
      user_agent TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_sessions_refresh_token ON sessions(refresh_token);

    -- Password reset tokens
    CREATE TABLE IF NOT EXISTS password_reset_tokens (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      used INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);

    -- User favorites (wishlist sync between web & mobile)
    CREATE TABLE IF NOT EXISTS user_favorites (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      listing_id INTEGER NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
      UNIQUE(user_id, listing_id)
    );
    CREATE INDEX IF NOT EXISTS idx_user_favorites_user ON user_favorites(user_id);
    CREATE INDEX IF NOT EXISTS idx_user_favorites_listing ON user_favorites(listing_id);

    -- Test drive bookings (synced between web & mobile)
    CREATE TABLE IF NOT EXISTS test_drive_bookings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      listing_id INTEGER NOT NULL,
      car_title TEXT NOT NULL DEFAULT '',
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      email TEXT,
      preferred_date TEXT,
      preferred_time TEXT,
      location_preference TEXT DEFAULT 'hub',
      notes TEXT,
      status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'confirmed', 'completed', 'cancelled')),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_bookings_user ON test_drive_bookings(user_id);
    CREATE INDEX IF NOT EXISTS idx_bookings_listing ON test_drive_bookings(listing_id);
    CREATE INDEX IF NOT EXISTS idx_bookings_status ON test_drive_bookings(status);
  `)
}

const seedCategories = () => {
  const count = db.prepare('SELECT COUNT(*) as count FROM categories').get().count
  if (count > 0) return

  const insert = db.prepare('INSERT INTO categories (name, slug, vehicle_type) VALUES (@name, @slug, @vehicleType)')
  const tx = db.transaction((items) => { for (const item of items) insert.run(item) })
  tx(defaultCategories)
}

const seedFilterDefinitions = () => {
  const count = db.prepare('SELECT COUNT(*) as count FROM filter_definitions').get().count
  if (count > 0) return

  const insert = db.prepare('INSERT INTO filter_definitions (key, label, type, options_json) VALUES (@key, @label, @type, @optionsJson)')
  const tx = db.transaction((items) => {
    for (const item of items) insert.run({ key: item.key, label: item.label, type: item.type, optionsJson: JSON.stringify(item.options) })
  })
  tx(defaultFilterDefinitions)
}

const seedCategoryFilterMap = () => {
  const count = db.prepare('SELECT COUNT(*) as count FROM category_filter_map').get().count
  if (count > 0) return

  const categories = db.prepare('SELECT id FROM categories').all()
  const filters = db.prepare('SELECT id FROM filter_definitions').all()
  const insert = db.prepare('INSERT OR IGNORE INTO category_filter_map (category_id, filter_id) VALUES (?, ?)')
  const tx = db.transaction(() => {
    for (const category of categories) {
      for (const filter of filters) {
        insert.run(category.id, filter.id)
      }
    }
  })
  tx()
}

const seedListings = () => {
  const count = db.prepare('SELECT COUNT(*) as count FROM listings').get().count
  if (count > 0) return

  const categoryByType = db.prepare('SELECT id, vehicle_type FROM categories').all().reduce((acc, row) => {
    acc[row.vehicle_type] = row.id
    return acc
  }, {})

  const insert = db.prepare(`
    INSERT INTO listings (
      category_id, listing_code, title, brand, model, variant,
      model_year, registration_year, vehicle_type, body_style,
      exterior_color, interior_color, listing_price_inr, negotiable,
      estimated_market_value_inr, ownership_type, seller_type,
      registration_state, registration_city, total_km_driven, mileage_kmpl,
      engine_type, engine_capacity_cc, power_bhp, transmission_type,
      fuel_type, battery_capacity_kwh, overall_condition_rating,
      service_history_available, airbags_count, infotainment_screen_size,
      location_city, location_state, dealer_rating, inspection_status,
      inspection_score, listing_status, featured_listing, is_splus, is_new_car, new_car_type,
      views_count, favorites_count, lead_count, promotion_tier, images_json, additional_notes
    ) VALUES (
      @categoryId, @listingCode, @title, @brand, @model, @variant,
      @modelYear, @registrationYear, @vehicleType, @bodyStyle,
      @exteriorColor, @interiorColor, @listingPriceInr, @negotiable,
      @estimatedMarketValueInr, @ownershipType, @sellerType,
      @registrationState, @registrationCity, @totalKmDriven, @mileageKmpl,
      @engineType, @engineCapacityCc, @powerBhp, @transmissionType,
      @fuelType, @batteryCapacityKwh, @overallConditionRating,
      @serviceHistoryAvailable, @airbagsCount, @infotainmentScreenSize,
      @locationCity, @locationState, @dealerRating, @inspectionStatus,
      @inspectionScore, @listingStatus, @featuredListing, @isSplus, @isNewCar, @newCarType,
      @viewsCount, @favoritesCount, @leadCount, @promotionTier, @imagesJson, @description
    )
  `)

  const tx = db.transaction((items) => {
    for (const item of items) {
      insert.run({
        ...item,
        isSplus: item.isSplus ?? 0,
        isNewCar: item.isNewCar ?? 0,
        newCarType: item.newCarType ?? null,
        categoryId: categoryByType[item.vehicleType] ?? categoryByType['SUV'] ?? null,
        imagesJson: JSON.stringify(item.images),
      })
    }
  })

  tx(sampleListings)
}

const seedNewCarListings = () => {
  const existing = db.prepare("SELECT COUNT(*) as count FROM listings WHERE is_new_car = 1").get().count
  if (existing > 0) return

  const categoryByType = db.prepare('SELECT id, vehicle_type FROM categories').all().reduce((acc, row) => {
    acc[row.vehicle_type] = row.id
    return acc
  }, {})

  const insert = db.prepare(`
    INSERT INTO listings (
      category_id, listing_code, title, brand, model, variant,
      model_year, registration_year, vehicle_type, body_style,
      exterior_color, interior_color, listing_price_inr, negotiable,
      estimated_market_value_inr, ownership_type, seller_type,
      registration_state, registration_city, total_km_driven, mileage_kmpl,
      engine_type, engine_capacity_cc, power_bhp, transmission_type,
      fuel_type, battery_capacity_kwh, overall_condition_rating,
      service_history_available, airbags_count, infotainment_screen_size,
      location_city, location_state, dealer_rating, inspection_status,
      inspection_score, listing_status, featured_listing, is_splus, is_new_car, new_car_type,
      views_count, favorites_count, lead_count, promotion_tier, images_json, additional_notes
    ) VALUES (
      @categoryId, @listingCode, @title, @brand, @model, @variant,
      @modelYear, @registrationYear, @vehicleType, @bodyStyle,
      @exteriorColor, @interiorColor, @listingPriceInr, @negotiable,
      @estimatedMarketValueInr, @ownershipType, @sellerType,
      @registrationState, @registrationCity, @totalKmDriven, @mileageKmpl,
      @engineType, @engineCapacityCc, @powerBhp, @transmissionType,
      @fuelType, @batteryCapacityKwh, @overallConditionRating,
      @serviceHistoryAvailable, @airbagsCount, @infotainmentScreenSize,
      @locationCity, @locationState, @dealerRating, @inspectionStatus,
      @inspectionScore, @listingStatus, @featuredListing, @isSplus, @isNewCar, @newCarType,
      @viewsCount, @favoritesCount, @leadCount, @promotionTier, @imagesJson, @description
    )
  `)

  const tx = db.transaction((items) => {
    for (const item of items) {
      insert.run({
        ...item,
        categoryId: categoryByType[item.bodyStyle] ?? categoryByType[item.vehicleType] ?? categoryByType['SUV'] ?? null,
        imagesJson: JSON.stringify(item.images),
      })
    }
  })

  tx(newCarListings)
}

const seedSiteConfig = () => {
  const insert = db.prepare('INSERT OR IGNORE INTO site_config (key, value) VALUES (?, ?)')

  const defaults = {
    site_name: JSON.stringify('SearchAnyCars'),
    hero: JSON.stringify({ title: 'Find Your Perfect Used Car', subtitle: 'Browse 12,000+ quality-inspected used cars with warranty, easy financing, and doorstep delivery across India' }),
    trust_bar: JSON.stringify([
      { icon: '🔍', label: '200+ Point Inspection', iconClass: 'trust-icon-blue' },
      { icon: '🔄', label: '7-Day Money Back', iconClass: 'trust-icon-green' },
      { icon: '🛡️', label: '1-Year Warranty', iconClass: 'trust-icon-blue' },
      { icon: '💰', label: 'Fixed Price — No Haggling', iconClass: 'trust-icon-orange' },
      { icon: '📋', label: 'Free RC Transfer', iconClass: 'trust-icon-green' },
    ]),
    budget_brackets: JSON.stringify([
      { label: 'Under ₹2L', max: 200000 },
      { label: '₹2-3L', min: 200000, max: 300000 },
      { label: '₹3-5L', min: 300000, max: 500000 },
      { label: '₹5-8L', min: 500000, max: 800000 },
      { label: '₹8-10L', min: 800000, max: 1000000 },
      { label: '₹10-15L', min: 1000000, max: 1500000 },
      { label: '₹15-20L', min: 1500000, max: 2000000 },
      { label: 'Above ₹20L', min: 2000000 },
    ]),
    body_types: JSON.stringify([
      { name: 'Hatchback', icon: '🚗', count: '420+' },
      { name: 'Sedan', icon: '🚘', count: '380+' },
      { name: 'SUV', icon: '🚙', count: '520+' },
      { name: 'MUV', icon: '🚐', count: '180+' },
      { name: 'Luxury Sedan', icon: '🏎️', count: '95+' },
      { name: 'Luxury SUV', icon: '🛻', count: '75+' },
    ]),
    fuel_types: JSON.stringify([
      { name: 'Petrol', icon: '⛽', count: '580+' },
      { name: 'Diesel', icon: '🛢️', count: '320+' },
      { name: 'CNG', icon: '💨', count: '95+' },
      { name: 'Electric', icon: '⚡', count: '45+' },
    ]),
    cities: JSON.stringify([
      { name: 'New Delhi', slug: 'new-delhi', count: '1,200+', image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=400&h=300&fit=crop' },
      { name: 'Mumbai', slug: 'mumbai', count: '1,800+', image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=400&h=300&fit=crop' },
      { name: 'Bengaluru', slug: 'bengaluru', count: '950+', image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=400&h=300&fit=crop' },
      { name: 'Chennai', slug: 'chennai', count: '720+', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=400&h=300&fit=crop' },
      { name: 'Hyderabad', slug: 'hyderabad', count: '680+', image: 'https://images.unsplash.com/photo-1526711657229-e7e080ed7aa1?w=400&h=300&fit=crop' },
      { name: 'Pune', slug: 'pune', count: '540+', image: 'https://images.unsplash.com/photo-1572782252655-9c8771392601?w=400&h=300&fit=crop' },
      { name: 'Ahmedabad', slug: 'ahmedabad', count: '420+', image: 'https://images.unsplash.com/photo-1585128792020-803d29415281?w=400&h=300&fit=crop' },
      { name: 'Jaipur', slug: 'jaipur', count: '380+', image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=400&h=300&fit=crop' },
      { name: 'Lucknow', slug: 'lucknow', count: '310+', image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&h=300&fit=crop' },
      { name: 'Kolkata', slug: 'kolkata', count: '650+', image: 'https://images.unsplash.com/photo-1558431382-27e303142255?w=400&h=300&fit=crop' },
      { name: 'Chandigarh', slug: 'chandigarh', count: '290+', image: 'https://images.unsplash.com/photo-1590075865003-e48277faa558?w=400&h=300&fit=crop' },
      { name: 'Kochi', slug: 'kochi', count: '260+', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=400&h=300&fit=crop' },
    ]),
    reviews: JSON.stringify([
      { name: 'Rahul S.', city: 'New Delhi', car: 'Hyundai Creta', text: 'Found the perfect Creta within 2 days. The inspection report gave me complete confidence.', rating: 5 },
      { name: 'Priya M.', city: 'Mumbai', car: 'Honda City', text: 'The fixed pricing was such a relief - no haggling! The 7-day return policy sealed the deal.', rating: 5 },
      { name: 'Vikram K.', city: 'Bengaluru', car: 'Tata Nexon', text: 'Best used car buying experience. The EMI calculator helped me plan my finances.', rating: 5 },
    ]),
    nav_items: JSON.stringify([
      { label: 'Home', path: '/' },
      { label: 'Buy Cars', path: '/search' },
      { label: 'S-Plus', path: '/splus' },
      { label: 'S-Plus New', path: '/splus-new' },
      { label: 'How It Works', path: '/how-it-works' },
      { label: 'About Us', path: '/about' },
      { label: 'FAQs', path: '/faq' },
      { label: 'Contact', path: '/contact' },
    ]),
    footer: JSON.stringify({
      brand_text: "India's most trusted used car platform. Quality-inspected cars with warranty & money-back guarantee.",
      columns: [
        { key: 'company', title: 'Company', links: [
          { label: 'About Us', to: '/about' },
          { label: 'How It Works', to: '/how-it-works' },
          { label: 'S-Plus Premium', to: '/splus' },
          { label: 'S-Plus New', to: '/splus-new' },
          { label: 'Contact Us', to: '/contact' },
        ]},
        { key: 'buy', title: 'Buy Cars', links: [
          { label: 'Maruti Suzuki', to: '/search?brand=Maruti+Suzuki' },
          { label: 'Hyundai', to: '/search?brand=Hyundai' },
          { label: 'Tata', to: '/search?brand=Tata' },
          { label: 'Honda', to: '/search?brand=Honda' },
          { label: 'All Brands', to: '/search' },
        ]},
        { key: 'browse', title: 'Browse By', links: [
          { label: 'SUVs', to: '/search?body_style=SUV' },
          { label: 'Sedans', to: '/search?body_style=Sedan' },
          { label: 'Hatchbacks', to: '/search?body_style=Hatchback' },
          { label: 'Electric', to: '/search?fuel_type=Electric' },
        ]},
        { key: 'support', title: 'Support', links: [
          { label: 'FAQs', to: '/faq' },
          { label: 'Warranty', to: '/faq' },
          { label: 'Privacy Policy', to: '/faq' },
          { label: 'Terms', to: '/faq' },
        ]},
      ]
    }),
    sell_cta: JSON.stringify({ title: 'Want to Sell Your Car?', description: 'List your car for free. Get the best price from verified buyers across India.', button_text: 'Sell Your Car' }),
    splus_banner: JSON.stringify({
      badge: 'S-Plus Premium',
      title: 'Experience Luxury, Pre-Owned',
      description: 'Handpicked premium cars with 300-point inspection, 2-year warranty, and dedicated concierge service.',
      features: [
        { icon: '◆', label: '300-Point Inspection' },
        { icon: '★', label: '2-Year Warranty' },
        { icon: '♢', label: 'White-Glove Delivery' },
        { icon: '↻', label: 'Personal Advisor' },
      ]
    }),
    spn_banner: JSON.stringify({
      badge: 'S-Plus New',
      title: 'Brand New. Zero Owners. Your Name First.',
      description: 'Premium unregistered, unused, and demo cars from authorized dealers. Full manufacturer warranty included.',
      features: [
        { icon: '◇', label: 'Factory Fresh' },
        { icon: '★', label: 'Full Warranty' },
        { icon: '◈', label: 'First Registration' },
        { icon: '⟐', label: 'White-Glove Delivery' },
      ]
    }),
    contact_info: JSON.stringify({ phone: '+91 98765 43210', whatsapp: '+91 98765 43210', email: 'hello@searchanycars.com', address: 'Koramangala, Bengaluru, Karnataka 560034' }),
  }

  for (const [key, value] of Object.entries(defaults)) {
    insert.run(key, value)
  }
}

const seedDefaultAdmin = () => {
  const existing = db.prepare("SELECT id FROM users WHERE role = 'admin' LIMIT 1").get()
  if (!existing) {
    const hash = bcrypt.hashSync(process.env.ADMIN_DEFAULT_PASSWORD || 'admin123', 12)
    db.prepare(
      "INSERT INTO users (email, name, password_hash, role, email_verified) VALUES (?, ?, ?, 'admin', 1)"
    ).run('admin@searchanycars.com', 'Admin', hash)
    console.log('Default admin created: admin@searchanycars.com')
  }
}

export const bootstrapDatabase = () => {
  createTables()
  seedCategories()
  seedFilterDefinitions()
  seedCategoryFilterMap()
  seedListings()
  seedNewCarListings()
  seedSiteConfig()
  seedDefaultAdmin()
}
